plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':entrypoints-rest')
    implementation project(':usecase')
    implementation project(':repository')
    implementation project(':drivenadapters-gemini')
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}
